/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Provider } from "@ethersproject/providers";

export declare namespace IDolomiteStructs {
  export type AccountInfoStruct = { owner: string; number: BigNumberish };

  export type AccountInfoStructOutput = [string, BigNumber] & {
    owner: string;
    number: BigNumber;
  };
}

export declare namespace IGenericTraderBase {
  export type TraderParamStruct = {
    traderType: BigNumberish;
    makerAccountIndex: BigNumberish;
    trader: string;
    tradeData: BytesLike;
  };

  export type TraderParamStructOutput = [number, BigNumber, string, string] & {
    traderType: number;
    makerAccountIndex: BigNumber;
    trader: string;
    tradeData: string;
  };
}

export declare namespace ILiquidatorProxyV6 {
  export type LiquidateParamsStruct = {
    solidAccount: IDolomiteStructs.AccountInfoStruct;
    liquidAccount: IDolomiteStructs.AccountInfoStruct;
    marketIdsPath: BigNumberish[];
    inputAmountWei: BigNumberish;
    minOutputAmountWei: BigNumberish;
    tradersPath: IGenericTraderBase.TraderParamStruct[];
    makerAccounts: IDolomiteStructs.AccountInfoStruct[];
    expirationTimestamp: BigNumberish;
    withdrawAllReward: boolean;
  };

  export type LiquidateParamsStructOutput = [
    IDolomiteStructs.AccountInfoStructOutput,
    IDolomiteStructs.AccountInfoStructOutput,
    BigNumber[],
    BigNumber,
    BigNumber,
    IGenericTraderBase.TraderParamStructOutput[],
    IDolomiteStructs.AccountInfoStructOutput[],
    BigNumber,
    boolean
  ] & {
    solidAccount: IDolomiteStructs.AccountInfoStructOutput;
    liquidAccount: IDolomiteStructs.AccountInfoStructOutput;
    marketIdsPath: BigNumber[];
    inputAmountWei: BigNumber;
    minOutputAmountWei: BigNumber;
    tradersPath: IGenericTraderBase.TraderParamStructOutput[];
    makerAccounts: IDolomiteStructs.AccountInfoStructOutput[];
    expirationTimestamp: BigNumber;
    withdrawAllReward: boolean;
  };
}

export interface LiquidatorProxyV6Interface extends utils.Interface {
  functions: {
    "DOLOMITE_MARGIN()": FunctionFragment;
    "DOLOMITE_MARGIN_OWNER()": FunctionFragment;
    "DOLOMITE_REGISTRY()": FunctionFragment;
    "EXPIRY()": FunctionFragment;
    "LIQUIDATOR_ASSET_REGISTRY()": FunctionFragment;
    "initialize()": FunctionFragment;
    "liquidate(((address,uint256),(address,uint256),uint256[],uint256,uint256,(uint8,uint256,address,bytes)[],(address,uint256)[],uint256,bool))": FunctionFragment;
    "liquidateViaProxyWithStrictInputMarket(((address,uint256),(address,uint256),uint256[],uint256,uint256,(uint8,uint256,address,bytes)[],(address,uint256)[],uint256,bool))": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "DOLOMITE_MARGIN"
      | "DOLOMITE_MARGIN_OWNER"
      | "DOLOMITE_REGISTRY"
      | "EXPIRY"
      | "LIQUIDATOR_ASSET_REGISTRY"
      | "initialize"
      | "liquidate"
      | "liquidateViaProxyWithStrictInputMarket"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "DOLOMITE_MARGIN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DOLOMITE_MARGIN_OWNER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DOLOMITE_REGISTRY",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "EXPIRY", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "LIQUIDATOR_ASSET_REGISTRY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "liquidate",
    values: [ILiquidatorProxyV6.LiquidateParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidateViaProxyWithStrictInputMarket",
    values: [ILiquidatorProxyV6.LiquidateParamsStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "DOLOMITE_MARGIN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DOLOMITE_MARGIN_OWNER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DOLOMITE_REGISTRY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "EXPIRY", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "LIQUIDATOR_ASSET_REGISTRY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "liquidate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "liquidateViaProxyWithStrictInputMarket",
    data: BytesLike
  ): Result;

  events: {
    "Initialized(uint8)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
}

export interface LiquidatorProxyV6 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: LiquidatorProxyV6Interface;

  functions: {
    DOLOMITE_MARGIN(overrides?: CallOverrides): Promise<[string]>;

    DOLOMITE_MARGIN_OWNER(overrides?: CallOverrides): Promise<[string]>;

    DOLOMITE_REGISTRY(overrides?: CallOverrides): Promise<[string]>;

    EXPIRY(overrides?: CallOverrides): Promise<[string]>;

    LIQUIDATOR_ASSET_REGISTRY(overrides?: CallOverrides): Promise<[string]>;

    initialize(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    liquidate(
      _liquidateParams: ILiquidatorProxyV6.LiquidateParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    liquidateViaProxyWithStrictInputMarket(
      _liquidateParams: ILiquidatorProxyV6.LiquidateParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  DOLOMITE_MARGIN(overrides?: CallOverrides): Promise<string>;

  DOLOMITE_MARGIN_OWNER(overrides?: CallOverrides): Promise<string>;

  DOLOMITE_REGISTRY(overrides?: CallOverrides): Promise<string>;

  EXPIRY(overrides?: CallOverrides): Promise<string>;

  LIQUIDATOR_ASSET_REGISTRY(overrides?: CallOverrides): Promise<string>;

  initialize(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  liquidate(
    _liquidateParams: ILiquidatorProxyV6.LiquidateParamsStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  liquidateViaProxyWithStrictInputMarket(
    _liquidateParams: ILiquidatorProxyV6.LiquidateParamsStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    DOLOMITE_MARGIN(overrides?: CallOverrides): Promise<string>;

    DOLOMITE_MARGIN_OWNER(overrides?: CallOverrides): Promise<string>;

    DOLOMITE_REGISTRY(overrides?: CallOverrides): Promise<string>;

    EXPIRY(overrides?: CallOverrides): Promise<string>;

    LIQUIDATOR_ASSET_REGISTRY(overrides?: CallOverrides): Promise<string>;

    initialize(overrides?: CallOverrides): Promise<void>;

    liquidate(
      _liquidateParams: ILiquidatorProxyV6.LiquidateParamsStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    liquidateViaProxyWithStrictInputMarket(
      _liquidateParams: ILiquidatorProxyV6.LiquidateParamsStruct,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  estimateGas: {
    DOLOMITE_MARGIN(overrides?: CallOverrides): Promise<BigNumber>;

    DOLOMITE_MARGIN_OWNER(overrides?: CallOverrides): Promise<BigNumber>;

    DOLOMITE_REGISTRY(overrides?: CallOverrides): Promise<BigNumber>;

    EXPIRY(overrides?: CallOverrides): Promise<BigNumber>;

    LIQUIDATOR_ASSET_REGISTRY(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    liquidate(
      _liquidateParams: ILiquidatorProxyV6.LiquidateParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    liquidateViaProxyWithStrictInputMarket(
      _liquidateParams: ILiquidatorProxyV6.LiquidateParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    DOLOMITE_MARGIN(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    DOLOMITE_MARGIN_OWNER(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    DOLOMITE_REGISTRY(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    EXPIRY(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    LIQUIDATOR_ASSET_REGISTRY(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    liquidate(
      _liquidateParams: ILiquidatorProxyV6.LiquidateParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    liquidateViaProxyWithStrictInputMarket(
      _liquidateParams: ILiquidatorProxyV6.LiquidateParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
