/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Provider } from "@ethersproject/providers";

export declare namespace IDolomiteStructs {
  export type DecimalStruct = { value: BigNumberish };

  export type DecimalStructOutput = [BigNumber] & { value: BigNumber };

  export type AccountInfoStruct = { owner: string; number: BigNumberish };
}

export declare namespace IGenericTraderBase {
  export type TraderParamStruct = {
    traderType: BigNumberish;
    makerAccountIndex: BigNumberish;
    trader: string;
    tradeData: BytesLike;
  };
}

export declare namespace ILiquidatorProxyV6 {
  export type LiquidateParamsStruct = {
    solidAccount: IDolomiteStructs.AccountInfoStruct;
    liquidAccount: IDolomiteStructs.AccountInfoStruct;
    marketIdsPath: BigNumberish[];
    inputAmountWei: BigNumberish;
    minOutputAmountWei: BigNumberish;
    tradersPath: IGenericTraderBase.TraderParamStruct[];
    makerAccounts: IDolomiteStructs.AccountInfoStruct[];
    expirationTimestamp: BigNumberish;
    withdrawAllReward: boolean;
  };
}

export interface LiquidatorProxyV6Interface extends utils.Interface {
  functions: {
    "DOLOMITE_MARGIN()": FunctionFragment;
    "DOLOMITE_MARGIN_OWNER()": FunctionFragment;
    "DOLOMITE_REGISTRY()": FunctionFragment;
    "EXPIRY()": FunctionFragment;
    "LIQUIDATOR_ASSET_REGISTRY()": FunctionFragment;
    "dolomiteRake()": FunctionFragment;
    "initialize()": FunctionFragment;
    "isPartialLiquidationSupportedByMarketId(uint256)": FunctionFragment;
    "isWhitelistedPartialLiquidator(address)": FunctionFragment;
    "liquidate(((address,uint256),(address,uint256),uint256[],uint256,uint256,(uint8,uint256,address,bytes)[],(address,uint256)[],uint256,bool))": FunctionFragment;
    "liquidateViaProxyWithStrictInputMarket(((address,uint256),(address,uint256),uint256[],uint256,uint256,(uint8,uint256,address,bytes)[],(address,uint256)[],uint256,bool))": FunctionFragment;
    "ownerInitializeV2((uint256),(uint256),address,uint256[])": FunctionFragment;
    "ownerSetDolomiteRake((uint256))": FunctionFragment;
    "ownerSetIsPartialLiquidator(address,bool)": FunctionFragment;
    "ownerSetMarketToPartialLiquidationSupported(uint256[],bool[])": FunctionFragment;
    "ownerSetPartialLiquidationThreshold((uint256))": FunctionFragment;
    "partialLiquidationThreshold()": FunctionFragment;
    "version()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "DOLOMITE_MARGIN"
      | "DOLOMITE_MARGIN_OWNER"
      | "DOLOMITE_REGISTRY"
      | "EXPIRY"
      | "LIQUIDATOR_ASSET_REGISTRY"
      | "dolomiteRake"
      | "initialize"
      | "isPartialLiquidationSupportedByMarketId"
      | "isWhitelistedPartialLiquidator"
      | "liquidate"
      | "liquidateViaProxyWithStrictInputMarket"
      | "ownerInitializeV2"
      | "ownerSetDolomiteRake"
      | "ownerSetIsPartialLiquidator"
      | "ownerSetMarketToPartialLiquidationSupported"
      | "ownerSetPartialLiquidationThreshold"
      | "partialLiquidationThreshold"
      | "version"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "DOLOMITE_MARGIN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DOLOMITE_MARGIN_OWNER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DOLOMITE_REGISTRY",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "EXPIRY", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "LIQUIDATOR_ASSET_REGISTRY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "dolomiteRake",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isPartialLiquidationSupportedByMarketId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isWhitelistedPartialLiquidator",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidate",
    values: [ILiquidatorProxyV6.LiquidateParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidateViaProxyWithStrictInputMarket",
    values: [ILiquidatorProxyV6.LiquidateParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerInitializeV2",
    values: [
      IDolomiteStructs.DecimalStruct,
      IDolomiteStructs.DecimalStruct,
      string,
      BigNumberish[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerSetDolomiteRake",
    values: [IDolomiteStructs.DecimalStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerSetIsPartialLiquidator",
    values: [string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerSetMarketToPartialLiquidationSupported",
    values: [BigNumberish[], boolean[]]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerSetPartialLiquidationThreshold",
    values: [IDolomiteStructs.DecimalStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "partialLiquidationThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "DOLOMITE_MARGIN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DOLOMITE_MARGIN_OWNER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DOLOMITE_REGISTRY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "EXPIRY", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "LIQUIDATOR_ASSET_REGISTRY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dolomiteRake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isPartialLiquidationSupportedByMarketId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isWhitelistedPartialLiquidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "liquidate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "liquidateViaProxyWithStrictInputMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerInitializeV2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerSetDolomiteRake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerSetIsPartialLiquidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerSetMarketToPartialLiquidationSupported",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerSetPartialLiquidationThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "partialLiquidationThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;

  events: {
    "DolomiteRakeSet((uint256))": EventFragment;
    "Initialized(uint8)": EventFragment;
    "MarketToPartialLiquidationSupportedSet(uint256[],bool[])": EventFragment;
    "PartialLiquidationThresholdSet((uint256))": EventFragment;
    "PartialLiquidatorSet(address,bool)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DolomiteRakeSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "MarketToPartialLiquidationSupportedSet"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "PartialLiquidationThresholdSet"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PartialLiquidatorSet"): EventFragment;
}

export interface LiquidatorProxyV6 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: LiquidatorProxyV6Interface;

  functions: {
    DOLOMITE_MARGIN(overrides?: CallOverrides): Promise<[string]>;

    DOLOMITE_MARGIN_OWNER(overrides?: CallOverrides): Promise<[string]>;

    DOLOMITE_REGISTRY(overrides?: CallOverrides): Promise<[string]>;

    EXPIRY(overrides?: CallOverrides): Promise<[string]>;

    LIQUIDATOR_ASSET_REGISTRY(overrides?: CallOverrides): Promise<[string]>;

    dolomiteRake(
      overrides?: CallOverrides
    ): Promise<[IDolomiteStructs.DecimalStructOutput]>;

    initialize(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    isPartialLiquidationSupportedByMarketId(
      _marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isWhitelistedPartialLiquidator(
      _account: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    liquidate(
      _liquidateParams: ILiquidatorProxyV6.LiquidateParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    liquidateViaProxyWithStrictInputMarket(
      _liquidateParams: ILiquidatorProxyV6.LiquidateParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    ownerInitializeV2(
      _dolomiteRake: IDolomiteStructs.DecimalStruct,
      _partialLiquidationThreshold: IDolomiteStructs.DecimalStruct,
      _initialPartialLiquidator: string,
      _initialPartialLiquidationMarketIds: BigNumberish[],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    ownerSetDolomiteRake(
      _dolomiteRake: IDolomiteStructs.DecimalStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    ownerSetIsPartialLiquidator(
      _partialLiquidator: string,
      _isPartialLiquidator: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    ownerSetMarketToPartialLiquidationSupported(
      _marketIds: BigNumberish[],
      _isSupported: boolean[],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    ownerSetPartialLiquidationThreshold(
      _partialLiquidationThreshold: IDolomiteStructs.DecimalStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    partialLiquidationThreshold(
      overrides?: CallOverrides
    ): Promise<[IDolomiteStructs.DecimalStructOutput]>;

    version(overrides?: CallOverrides): Promise<[number]>;
  };

  DOLOMITE_MARGIN(overrides?: CallOverrides): Promise<string>;

  DOLOMITE_MARGIN_OWNER(overrides?: CallOverrides): Promise<string>;

  DOLOMITE_REGISTRY(overrides?: CallOverrides): Promise<string>;

  EXPIRY(overrides?: CallOverrides): Promise<string>;

  LIQUIDATOR_ASSET_REGISTRY(overrides?: CallOverrides): Promise<string>;

  dolomiteRake(
    overrides?: CallOverrides
  ): Promise<IDolomiteStructs.DecimalStructOutput>;

  initialize(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  isPartialLiquidationSupportedByMarketId(
    _marketId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isWhitelistedPartialLiquidator(
    _account: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  liquidate(
    _liquidateParams: ILiquidatorProxyV6.LiquidateParamsStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  liquidateViaProxyWithStrictInputMarket(
    _liquidateParams: ILiquidatorProxyV6.LiquidateParamsStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  ownerInitializeV2(
    _dolomiteRake: IDolomiteStructs.DecimalStruct,
    _partialLiquidationThreshold: IDolomiteStructs.DecimalStruct,
    _initialPartialLiquidator: string,
    _initialPartialLiquidationMarketIds: BigNumberish[],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  ownerSetDolomiteRake(
    _dolomiteRake: IDolomiteStructs.DecimalStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  ownerSetIsPartialLiquidator(
    _partialLiquidator: string,
    _isPartialLiquidator: boolean,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  ownerSetMarketToPartialLiquidationSupported(
    _marketIds: BigNumberish[],
    _isSupported: boolean[],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  ownerSetPartialLiquidationThreshold(
    _partialLiquidationThreshold: IDolomiteStructs.DecimalStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  partialLiquidationThreshold(
    overrides?: CallOverrides
  ): Promise<IDolomiteStructs.DecimalStructOutput>;

  version(overrides?: CallOverrides): Promise<number>;

  callStatic: {
    DOLOMITE_MARGIN(overrides?: CallOverrides): Promise<string>;

    DOLOMITE_MARGIN_OWNER(overrides?: CallOverrides): Promise<string>;

    DOLOMITE_REGISTRY(overrides?: CallOverrides): Promise<string>;

    EXPIRY(overrides?: CallOverrides): Promise<string>;

    LIQUIDATOR_ASSET_REGISTRY(overrides?: CallOverrides): Promise<string>;

    dolomiteRake(
      overrides?: CallOverrides
    ): Promise<IDolomiteStructs.DecimalStructOutput>;

    initialize(overrides?: CallOverrides): Promise<void>;

    isPartialLiquidationSupportedByMarketId(
      _marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isWhitelistedPartialLiquidator(
      _account: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    liquidate(
      _liquidateParams: ILiquidatorProxyV6.LiquidateParamsStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    liquidateViaProxyWithStrictInputMarket(
      _liquidateParams: ILiquidatorProxyV6.LiquidateParamsStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    ownerInitializeV2(
      _dolomiteRake: IDolomiteStructs.DecimalStruct,
      _partialLiquidationThreshold: IDolomiteStructs.DecimalStruct,
      _initialPartialLiquidator: string,
      _initialPartialLiquidationMarketIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    ownerSetDolomiteRake(
      _dolomiteRake: IDolomiteStructs.DecimalStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    ownerSetIsPartialLiquidator(
      _partialLiquidator: string,
      _isPartialLiquidator: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    ownerSetMarketToPartialLiquidationSupported(
      _marketIds: BigNumberish[],
      _isSupported: boolean[],
      overrides?: CallOverrides
    ): Promise<void>;

    ownerSetPartialLiquidationThreshold(
      _partialLiquidationThreshold: IDolomiteStructs.DecimalStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    partialLiquidationThreshold(
      overrides?: CallOverrides
    ): Promise<IDolomiteStructs.DecimalStructOutput>;

    version(overrides?: CallOverrides): Promise<number>;
  };

  estimateGas: {
    DOLOMITE_MARGIN(overrides?: CallOverrides): Promise<BigNumber>;

    DOLOMITE_MARGIN_OWNER(overrides?: CallOverrides): Promise<BigNumber>;

    DOLOMITE_REGISTRY(overrides?: CallOverrides): Promise<BigNumber>;

    EXPIRY(overrides?: CallOverrides): Promise<BigNumber>;

    LIQUIDATOR_ASSET_REGISTRY(overrides?: CallOverrides): Promise<BigNumber>;

    dolomiteRake(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    isPartialLiquidationSupportedByMarketId(
      _marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isWhitelistedPartialLiquidator(
      _account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    liquidate(
      _liquidateParams: ILiquidatorProxyV6.LiquidateParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    liquidateViaProxyWithStrictInputMarket(
      _liquidateParams: ILiquidatorProxyV6.LiquidateParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    ownerInitializeV2(
      _dolomiteRake: IDolomiteStructs.DecimalStruct,
      _partialLiquidationThreshold: IDolomiteStructs.DecimalStruct,
      _initialPartialLiquidator: string,
      _initialPartialLiquidationMarketIds: BigNumberish[],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    ownerSetDolomiteRake(
      _dolomiteRake: IDolomiteStructs.DecimalStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    ownerSetIsPartialLiquidator(
      _partialLiquidator: string,
      _isPartialLiquidator: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    ownerSetMarketToPartialLiquidationSupported(
      _marketIds: BigNumberish[],
      _isSupported: boolean[],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    ownerSetPartialLiquidationThreshold(
      _partialLiquidationThreshold: IDolomiteStructs.DecimalStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    partialLiquidationThreshold(overrides?: CallOverrides): Promise<BigNumber>;

    version(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    DOLOMITE_MARGIN(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    DOLOMITE_MARGIN_OWNER(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    DOLOMITE_REGISTRY(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    EXPIRY(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    LIQUIDATOR_ASSET_REGISTRY(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    dolomiteRake(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    initialize(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    isPartialLiquidationSupportedByMarketId(
      _marketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isWhitelistedPartialLiquidator(
      _account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    liquidate(
      _liquidateParams: ILiquidatorProxyV6.LiquidateParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    liquidateViaProxyWithStrictInputMarket(
      _liquidateParams: ILiquidatorProxyV6.LiquidateParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    ownerInitializeV2(
      _dolomiteRake: IDolomiteStructs.DecimalStruct,
      _partialLiquidationThreshold: IDolomiteStructs.DecimalStruct,
      _initialPartialLiquidator: string,
      _initialPartialLiquidationMarketIds: BigNumberish[],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    ownerSetDolomiteRake(
      _dolomiteRake: IDolomiteStructs.DecimalStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    ownerSetIsPartialLiquidator(
      _partialLiquidator: string,
      _isPartialLiquidator: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    ownerSetMarketToPartialLiquidationSupported(
      _marketIds: BigNumberish[],
      _isSupported: boolean[],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    ownerSetPartialLiquidationThreshold(
      _partialLiquidationThreshold: IDolomiteStructs.DecimalStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    partialLiquidationThreshold(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    version(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
